//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.261
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UMR.Saniteri.DataFactory.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UMR.Saniteri.DataFactory.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USE [SaniteriMain]
        ///GO
        ////****** Object:  Table [dbo].[can_eventcodes]    Script Date: 03/04/2012 18:11:54 ******/
        ///INSERT [dbo].[can_eventcodes] ([event_type], [description]) VALUES (0, N&apos;Monitored Passage&apos;)
        ///INSERT [dbo].[can_eventcodes] ([event_type], [description]) VALUES (1, N&apos;Refuse Access&apos;)
        ///INSERT [dbo].[can_eventcodes] ([event_type], [description]) VALUES (2, N&apos;Maintenance Access&apos;)
        ///INSERT [dbo].[can_eventcodes] ([event_type], [description]) VALUES (3, N&apos;Refuse Bag Full&apos;)
        ///INSERT [dbo].[can_eventcod [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SaniteriMain_DefaultData {
            get {
                return ResourceManager.GetString("SaniteriMain_DefaultData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GO
        ///CREATE TABLE [dbo].[can_users](
        ///	[user_id] [varchar](50) NOT NULL,
        ///	[first_name] [nvarchar](50) NULL,
        ///	[last_name] [nvarchar](50) NULL,
        ///	[title] [nvarchar](50) NULL,
        ///	[options] [int] NULL,
        /// CONSTRAINT [PK_can_users] PRIMARY KEY CLUSTERED 
        ///(
        ///	[user_id] ASC
        ///)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
        ///) ON [PRIMARY]
        ///GO
        ///SET ANSI_PADDING OFF
        ///GO
        ////****** Object:  Table [dbo].[can_statuscode]    Script Da [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SaniteriMain_SQLScript {
            get {
                return ResourceManager.GetString("SaniteriMain_SQLScript", resourceCulture);
            }
        }
    }
}
