//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("SaniteriEntities", "FK_can_command_can_inventory", "can_inventory", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(UMR.Saniteri.Data.can_inventory), "can_command", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(UMR.Saniteri.Data.can_command), true)]
[assembly: EdmRelationshipAttribute("SaniteriEntities", "FK_can_EventsLog_can_EventCodes", "can_eventcodes", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(UMR.Saniteri.Data.can_eventcodes), "can_transaction_log", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(UMR.Saniteri.Data.can_transaction_log), true)]
[assembly: EdmRelationshipAttribute("SaniteriEntities", "FK_can_maintenance_can_inventory", "can_inventory", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(UMR.Saniteri.Data.can_inventory), "can_maintenance", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(UMR.Saniteri.Data.can_maintenance), true)]
[assembly: EdmRelationshipAttribute("SaniteriEntities", "FK_can_status_can_inventory", "can_inventory", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(UMR.Saniteri.Data.can_inventory), "can_status", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(UMR.Saniteri.Data.can_status), true)]
[assembly: EdmRelationshipAttribute("SaniteriEntities", "FK_can_transaction_log_can_inventory", "can_inventory", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(UMR.Saniteri.Data.can_inventory), "can_transaction_log", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(UMR.Saniteri.Data.can_transaction_log), true)]
[assembly: EdmRelationshipAttribute("SaniteriEntities", "FK_can_Status_can_StatusCode", "can_statuscode", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(UMR.Saniteri.Data.can_statuscode), "can_status", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(UMR.Saniteri.Data.can_status), true)]

#endregion

namespace UMR.Saniteri.Data
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class SaniteriModelEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new SaniteriModelEntities object using the connection string found in the 'SaniteriModelEntities' section of the application configuration file.
        /// </summary>
        public SaniteriModelEntities() : base("name=SaniteriModelEntities", "SaniteriModelEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new SaniteriModelEntities object.
        /// </summary>
        public SaniteriModelEntities(string connectionString) : base(connectionString, "SaniteriModelEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new SaniteriModelEntities object.
        /// </summary>
        public SaniteriModelEntities(EntityConnection connection) : base(connection, "SaniteriModelEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<can_command> can_command
        {
            get
            {
                if ((_can_command == null))
                {
                    _can_command = base.CreateObjectSet<can_command>("can_command");
                }
                return _can_command;
            }
        }
        private ObjectSet<can_command> _can_command;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<can_eventcodes> can_eventcodes
        {
            get
            {
                if ((_can_eventcodes == null))
                {
                    _can_eventcodes = base.CreateObjectSet<can_eventcodes>("can_eventcodes");
                }
                return _can_eventcodes;
            }
        }
        private ObjectSet<can_eventcodes> _can_eventcodes;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<can_inventory> can_inventory
        {
            get
            {
                if ((_can_inventory == null))
                {
                    _can_inventory = base.CreateObjectSet<can_inventory>("can_inventory");
                }
                return _can_inventory;
            }
        }
        private ObjectSet<can_inventory> _can_inventory;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<can_maintenance> can_maintenance
        {
            get
            {
                if ((_can_maintenance == null))
                {
                    _can_maintenance = base.CreateObjectSet<can_maintenance>("can_maintenance");
                }
                return _can_maintenance;
            }
        }
        private ObjectSet<can_maintenance> _can_maintenance;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<can_status> can_status
        {
            get
            {
                if ((_can_status == null))
                {
                    _can_status = base.CreateObjectSet<can_status>("can_status");
                }
                return _can_status;
            }
        }
        private ObjectSet<can_status> _can_status;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<can_statuscode> can_statuscode
        {
            get
            {
                if ((_can_statuscode == null))
                {
                    _can_statuscode = base.CreateObjectSet<can_statuscode>("can_statuscode");
                }
                return _can_statuscode;
            }
        }
        private ObjectSet<can_statuscode> _can_statuscode;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<can_transaction_log> can_transaction_log
        {
            get
            {
                if ((_can_transaction_log == null))
                {
                    _can_transaction_log = base.CreateObjectSet<can_transaction_log>("can_transaction_log");
                }
                return _can_transaction_log;
            }
        }
        private ObjectSet<can_transaction_log> _can_transaction_log;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<can_users> can_users
        {
            get
            {
                if ((_can_users == null))
                {
                    _can_users = base.CreateObjectSet<can_users>("can_users");
                }
                return _can_users;
            }
        }
        private ObjectSet<can_users> _can_users;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the can_command EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTocan_command(can_command can_command)
        {
            base.AddObject("can_command", can_command);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the can_eventcodes EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTocan_eventcodes(can_eventcodes can_eventcodes)
        {
            base.AddObject("can_eventcodes", can_eventcodes);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the can_inventory EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTocan_inventory(can_inventory can_inventory)
        {
            base.AddObject("can_inventory", can_inventory);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the can_maintenance EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTocan_maintenance(can_maintenance can_maintenance)
        {
            base.AddObject("can_maintenance", can_maintenance);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the can_status EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTocan_status(can_status can_status)
        {
            base.AddObject("can_status", can_status);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the can_statuscode EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTocan_statuscode(can_statuscode can_statuscode)
        {
            base.AddObject("can_statuscode", can_statuscode);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the can_transaction_log EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTocan_transaction_log(can_transaction_log can_transaction_log)
        {
            base.AddObject("can_transaction_log", can_transaction_log);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the can_users EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTocan_users(can_users can_users)
        {
            base.AddObject("can_users", can_users);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="SaniteriEntities", Name="can_command")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class can_command : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new can_command object.
        /// </summary>
        /// <param name="seqno">Initial value of the seqno property.</param>
        /// <param name="can_id">Initial value of the can_id property.</param>
        /// <param name="can_lid_status">Initial value of the can_lid_status property.</param>
        /// <param name="command_timestamp">Initial value of the command_timestamp property.</param>
        public static can_command Createcan_command(global::System.Int32 seqno, global::System.Int64 can_id, global::System.Byte can_lid_status, global::System.DateTime command_timestamp)
        {
            can_command can_command = new can_command();
            can_command.seqno = seqno;
            can_command.can_id = can_id;
            can_command.can_lid_status = can_lid_status;
            can_command.command_timestamp = command_timestamp;
            return can_command;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 seqno
        {
            get
            {
                return _seqno;
            }
            set
            {
                if (_seqno != value)
                {
                    OnseqnoChanging(value);
                    ReportPropertyChanging("seqno");
                    _seqno = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("seqno");
                    OnseqnoChanged();
                }
            }
        }
        private global::System.Int32 _seqno;
        partial void OnseqnoChanging(global::System.Int32 value);
        partial void OnseqnoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> command_id
        {
            get
            {
                return _command_id;
            }
            set
            {
                Oncommand_idChanging(value);
                ReportPropertyChanging("command_id");
                _command_id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("command_id");
                Oncommand_idChanged();
            }
        }
        private Nullable<global::System.Int32> _command_id;
        partial void Oncommand_idChanging(Nullable<global::System.Int32> value);
        partial void Oncommand_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 can_id
        {
            get
            {
                return _can_id;
            }
            set
            {
                Oncan_idChanging(value);
                ReportPropertyChanging("can_id");
                _can_id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("can_id");
                Oncan_idChanged();
            }
        }
        private global::System.Int64 _can_id;
        partial void Oncan_idChanging(global::System.Int64 value);
        partial void Oncan_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Byte can_lid_status
        {
            get
            {
                return _can_lid_status;
            }
            set
            {
                Oncan_lid_statusChanging(value);
                ReportPropertyChanging("can_lid_status");
                _can_lid_status = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("can_lid_status");
                Oncan_lid_statusChanged();
            }
        }
        private global::System.Byte _can_lid_status;
        partial void Oncan_lid_statusChanging(global::System.Byte value);
        partial void Oncan_lid_statusChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime command_timestamp
        {
            get
            {
                return _command_timestamp;
            }
            set
            {
                Oncommand_timestampChanging(value);
                ReportPropertyChanging("command_timestamp");
                _command_timestamp = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("command_timestamp");
                Oncommand_timestampChanged();
            }
        }
        private global::System.DateTime _command_timestamp;
        partial void Oncommand_timestampChanging(global::System.DateTime value);
        partial void Oncommand_timestampChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("SaniteriEntities", "FK_can_command_can_inventory", "can_inventory")]
        public can_inventory can_inventory
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<can_inventory>("SaniteriEntities.FK_can_command_can_inventory", "can_inventory").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<can_inventory>("SaniteriEntities.FK_can_command_can_inventory", "can_inventory").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<can_inventory> can_inventoryReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<can_inventory>("SaniteriEntities.FK_can_command_can_inventory", "can_inventory");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<can_inventory>("SaniteriEntities.FK_can_command_can_inventory", "can_inventory", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="SaniteriEntities", Name="can_eventcodes")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class can_eventcodes : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new can_eventcodes object.
        /// </summary>
        /// <param name="event_type">Initial value of the event_type property.</param>
        public static can_eventcodes Createcan_eventcodes(global::System.Int32 event_type)
        {
            can_eventcodes can_eventcodes = new can_eventcodes();
            can_eventcodes.event_type = event_type;
            return can_eventcodes;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 event_type
        {
            get
            {
                return _event_type;
            }
            set
            {
                if (_event_type != value)
                {
                    Onevent_typeChanging(value);
                    ReportPropertyChanging("event_type");
                    _event_type = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("event_type");
                    Onevent_typeChanged();
                }
            }
        }
        private global::System.Int32 _event_type;
        partial void Onevent_typeChanging(global::System.Int32 value);
        partial void Onevent_typeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String description
        {
            get
            {
                return _description;
            }
            set
            {
                OndescriptionChanging(value);
                ReportPropertyChanging("description");
                _description = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("description");
                OndescriptionChanged();
            }
        }
        private global::System.String _description;
        partial void OndescriptionChanging(global::System.String value);
        partial void OndescriptionChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("SaniteriEntities", "FK_can_EventsLog_can_EventCodes", "can_transaction_log")]
        public EntityCollection<can_transaction_log> can_transaction_log
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<can_transaction_log>("SaniteriEntities.FK_can_EventsLog_can_EventCodes", "can_transaction_log");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<can_transaction_log>("SaniteriEntities.FK_can_EventsLog_can_EventCodes", "can_transaction_log", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="SaniteriEntities", Name="can_inventory")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class can_inventory : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new can_inventory object.
        /// </summary>
        /// <param name="can_id">Initial value of the can_id property.</param>
        public static can_inventory Createcan_inventory(global::System.Int64 can_id)
        {
            can_inventory can_inventory = new can_inventory();
            can_inventory.can_id = can_id;
            return can_inventory;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 can_id
        {
            get
            {
                return _can_id;
            }
            set
            {
                if (_can_id != value)
                {
                    Oncan_idChanging(value);
                    ReportPropertyChanging("can_id");
                    _can_id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("can_id");
                    Oncan_idChanged();
                }
            }
        }
        private global::System.Int64 _can_id;
        partial void Oncan_idChanging(global::System.Int64 value);
        partial void Oncan_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> production_date
        {
            get
            {
                return _production_date;
            }
            set
            {
                Onproduction_dateChanging(value);
                ReportPropertyChanging("production_date");
                _production_date = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("production_date");
                Onproduction_dateChanged();
            }
        }
        private Nullable<global::System.DateTime> _production_date;
        partial void Onproduction_dateChanging(Nullable<global::System.DateTime> value);
        partial void Onproduction_dateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> in_service_date
        {
            get
            {
                return _in_service_date;
            }
            set
            {
                Onin_service_dateChanging(value);
                ReportPropertyChanging("in_service_date");
                _in_service_date = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("in_service_date");
                Onin_service_dateChanged();
            }
        }
        private Nullable<global::System.DateTime> _in_service_date;
        partial void Onin_service_dateChanging(Nullable<global::System.DateTime> value);
        partial void Onin_service_dateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String street
        {
            get
            {
                return _street;
            }
            set
            {
                OnstreetChanging(value);
                ReportPropertyChanging("street");
                _street = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("street");
                OnstreetChanged();
            }
        }
        private global::System.String _street;
        partial void OnstreetChanging(global::System.String value);
        partial void OnstreetChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String additional
        {
            get
            {
                return _additional;
            }
            set
            {
                OnadditionalChanging(value);
                ReportPropertyChanging("additional");
                _additional = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("additional");
                OnadditionalChanged();
            }
        }
        private global::System.String _additional;
        partial void OnadditionalChanging(global::System.String value);
        partial void OnadditionalChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String city
        {
            get
            {
                return _city;
            }
            set
            {
                OncityChanging(value);
                ReportPropertyChanging("city");
                _city = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("city");
                OncityChanged();
            }
        }
        private global::System.String _city;
        partial void OncityChanging(global::System.String value);
        partial void OncityChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String state
        {
            get
            {
                return _state;
            }
            set
            {
                OnstateChanging(value);
                ReportPropertyChanging("state");
                _state = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("state");
                OnstateChanged();
            }
        }
        private global::System.String _state;
        partial void OnstateChanging(global::System.String value);
        partial void OnstateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String zip
        {
            get
            {
                return _zip;
            }
            set
            {
                OnzipChanging(value);
                ReportPropertyChanging("zip");
                _zip = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("zip");
                OnzipChanged();
            }
        }
        private global::System.String _zip;
        partial void OnzipChanging(global::System.String value);
        partial void OnzipChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String floor
        {
            get
            {
                return _floor;
            }
            set
            {
                OnfloorChanging(value);
                ReportPropertyChanging("floor");
                _floor = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("floor");
                OnfloorChanged();
            }
        }
        private global::System.String _floor;
        partial void OnfloorChanging(global::System.String value);
        partial void OnfloorChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String room
        {
            get
            {
                return _room;
            }
            set
            {
                OnroomChanging(value);
                ReportPropertyChanging("room");
                _room = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("room");
                OnroomChanged();
            }
        }
        private global::System.String _room;
        partial void OnroomChanging(global::System.String value);
        partial void OnroomChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String custom_1
        {
            get
            {
                return _custom_1;
            }
            set
            {
                Oncustom_1Changing(value);
                ReportPropertyChanging("custom_1");
                _custom_1 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("custom_1");
                Oncustom_1Changed();
            }
        }
        private global::System.String _custom_1;
        partial void Oncustom_1Changing(global::System.String value);
        partial void Oncustom_1Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String custom_2
        {
            get
            {
                return _custom_2;
            }
            set
            {
                Oncustom_2Changing(value);
                ReportPropertyChanging("custom_2");
                _custom_2 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("custom_2");
                Oncustom_2Changed();
            }
        }
        private global::System.String _custom_2;
        partial void Oncustom_2Changing(global::System.String value);
        partial void Oncustom_2Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String custom_3
        {
            get
            {
                return _custom_3;
            }
            set
            {
                Oncustom_3Changing(value);
                ReportPropertyChanging("custom_3");
                _custom_3 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("custom_3");
                Oncustom_3Changed();
            }
        }
        private global::System.String _custom_3;
        partial void Oncustom_3Changing(global::System.String value);
        partial void Oncustom_3Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ip_address
        {
            get
            {
                return _ip_address;
            }
            set
            {
                Onip_addressChanging(value);
                ReportPropertyChanging("ip_address");
                _ip_address = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ip_address");
                Onip_addressChanged();
            }
        }
        private global::System.String _ip_address;
        partial void Onip_addressChanging(global::System.String value);
        partial void Onip_addressChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("SaniteriEntities", "FK_can_command_can_inventory", "can_command")]
        public EntityCollection<can_command> can_command
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<can_command>("SaniteriEntities.FK_can_command_can_inventory", "can_command");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<can_command>("SaniteriEntities.FK_can_command_can_inventory", "can_command", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("SaniteriEntities", "FK_can_maintenance_can_inventory", "can_maintenance")]
        public EntityCollection<can_maintenance> can_maintenance
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<can_maintenance>("SaniteriEntities.FK_can_maintenance_can_inventory", "can_maintenance");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<can_maintenance>("SaniteriEntities.FK_can_maintenance_can_inventory", "can_maintenance", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("SaniteriEntities", "FK_can_status_can_inventory", "can_status")]
        public EntityCollection<can_status> can_status
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<can_status>("SaniteriEntities.FK_can_status_can_inventory", "can_status");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<can_status>("SaniteriEntities.FK_can_status_can_inventory", "can_status", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("SaniteriEntities", "FK_can_transaction_log_can_inventory", "can_transaction_log")]
        public EntityCollection<can_transaction_log> can_transaction_log
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<can_transaction_log>("SaniteriEntities.FK_can_transaction_log_can_inventory", "can_transaction_log");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<can_transaction_log>("SaniteriEntities.FK_can_transaction_log_can_inventory", "can_transaction_log", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="SaniteriEntities", Name="can_maintenance")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class can_maintenance : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new can_maintenance object.
        /// </summary>
        /// <param name="can_id">Initial value of the can_id property.</param>
        /// <param name="service_date">Initial value of the service_date property.</param>
        public static can_maintenance Createcan_maintenance(global::System.Int64 can_id, global::System.DateTime service_date)
        {
            can_maintenance can_maintenance = new can_maintenance();
            can_maintenance.can_id = can_id;
            can_maintenance.service_date = service_date;
            return can_maintenance;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 can_id
        {
            get
            {
                return _can_id;
            }
            set
            {
                if (_can_id != value)
                {
                    Oncan_idChanging(value);
                    ReportPropertyChanging("can_id");
                    _can_id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("can_id");
                    Oncan_idChanged();
                }
            }
        }
        private global::System.Int64 _can_id;
        partial void Oncan_idChanging(global::System.Int64 value);
        partial void Oncan_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime service_date
        {
            get
            {
                return _service_date;
            }
            set
            {
                if (_service_date != value)
                {
                    Onservice_dateChanging(value);
                    ReportPropertyChanging("service_date");
                    _service_date = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("service_date");
                    Onservice_dateChanged();
                }
            }
        }
        private global::System.DateTime _service_date;
        partial void Onservice_dateChanging(global::System.DateTime value);
        partial void Onservice_dateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String service_performed
        {
            get
            {
                return _service_performed;
            }
            set
            {
                Onservice_performedChanging(value);
                ReportPropertyChanging("service_performed");
                _service_performed = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("service_performed");
                Onservice_performedChanged();
            }
        }
        private global::System.String _service_performed;
        partial void Onservice_performedChanging(global::System.String value);
        partial void Onservice_performedChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("SaniteriEntities", "FK_can_maintenance_can_inventory", "can_inventory")]
        public can_inventory can_inventory
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<can_inventory>("SaniteriEntities.FK_can_maintenance_can_inventory", "can_inventory").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<can_inventory>("SaniteriEntities.FK_can_maintenance_can_inventory", "can_inventory").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<can_inventory> can_inventoryReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<can_inventory>("SaniteriEntities.FK_can_maintenance_can_inventory", "can_inventory");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<can_inventory>("SaniteriEntities.FK_can_maintenance_can_inventory", "can_inventory", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="SaniteriEntities", Name="can_status")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class can_status : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new can_status object.
        /// </summary>
        /// <param name="seqno">Initial value of the seqno property.</param>
        /// <param name="can_id">Initial value of the can_id property.</param>
        public static can_status Createcan_status(global::System.Guid seqno, global::System.Int64 can_id)
        {
            can_status can_status = new can_status();
            can_status.seqno = seqno;
            can_status.can_id = can_id;
            return can_status;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid seqno
        {
            get
            {
                return _seqno;
            }
            set
            {
                if (_seqno != value)
                {
                    OnseqnoChanging(value);
                    ReportPropertyChanging("seqno");
                    _seqno = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("seqno");
                    OnseqnoChanged();
                }
            }
        }
        private global::System.Guid _seqno;
        partial void OnseqnoChanging(global::System.Guid value);
        partial void OnseqnoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 can_id
        {
            get
            {
                return _can_id;
            }
            set
            {
                Oncan_idChanging(value);
                ReportPropertyChanging("can_id");
                _can_id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("can_id");
                Oncan_idChanged();
            }
        }
        private global::System.Int64 _can_id;
        partial void Oncan_idChanging(global::System.Int64 value);
        partial void Oncan_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> status_type
        {
            get
            {
                return _status_type;
            }
            set
            {
                Onstatus_typeChanging(value);
                ReportPropertyChanging("status_type");
                _status_type = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("status_type");
                Onstatus_typeChanged();
            }
        }
        private Nullable<global::System.Int32> _status_type;
        partial void Onstatus_typeChanging(Nullable<global::System.Int32> value);
        partial void Onstatus_typeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> edate
        {
            get
            {
                return _edate;
            }
            set
            {
                OnedateChanging(value);
                ReportPropertyChanging("edate");
                _edate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("edate");
                OnedateChanged();
            }
        }
        private Nullable<global::System.DateTime> _edate;
        partial void OnedateChanging(Nullable<global::System.DateTime> value);
        partial void OnedateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String status_description
        {
            get
            {
                return _status_description;
            }
            set
            {
                Onstatus_descriptionChanging(value);
                ReportPropertyChanging("status_description");
                _status_description = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("status_description");
                Onstatus_descriptionChanged();
            }
        }
        private global::System.String _status_description;
        partial void Onstatus_descriptionChanging(global::System.String value);
        partial void Onstatus_descriptionChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("SaniteriEntities", "FK_can_status_can_inventory", "can_inventory")]
        public can_inventory can_inventory
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<can_inventory>("SaniteriEntities.FK_can_status_can_inventory", "can_inventory").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<can_inventory>("SaniteriEntities.FK_can_status_can_inventory", "can_inventory").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<can_inventory> can_inventoryReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<can_inventory>("SaniteriEntities.FK_can_status_can_inventory", "can_inventory");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<can_inventory>("SaniteriEntities.FK_can_status_can_inventory", "can_inventory", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("SaniteriEntities", "FK_can_Status_can_StatusCode", "can_statuscode")]
        public can_statuscode can_statuscode
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<can_statuscode>("SaniteriEntities.FK_can_Status_can_StatusCode", "can_statuscode").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<can_statuscode>("SaniteriEntities.FK_can_Status_can_StatusCode", "can_statuscode").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<can_statuscode> can_statuscodeReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<can_statuscode>("SaniteriEntities.FK_can_Status_can_StatusCode", "can_statuscode");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<can_statuscode>("SaniteriEntities.FK_can_Status_can_StatusCode", "can_statuscode", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="SaniteriEntities", Name="can_statuscode")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class can_statuscode : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new can_statuscode object.
        /// </summary>
        /// <param name="status_type">Initial value of the status_type property.</param>
        public static can_statuscode Createcan_statuscode(global::System.Int32 status_type)
        {
            can_statuscode can_statuscode = new can_statuscode();
            can_statuscode.status_type = status_type;
            return can_statuscode;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 status_type
        {
            get
            {
                return _status_type;
            }
            set
            {
                if (_status_type != value)
                {
                    Onstatus_typeChanging(value);
                    ReportPropertyChanging("status_type");
                    _status_type = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("status_type");
                    Onstatus_typeChanged();
                }
            }
        }
        private global::System.Int32 _status_type;
        partial void Onstatus_typeChanging(global::System.Int32 value);
        partial void Onstatus_typeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String description
        {
            get
            {
                return _description;
            }
            set
            {
                OndescriptionChanging(value);
                ReportPropertyChanging("description");
                _description = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("description");
                OndescriptionChanged();
            }
        }
        private global::System.String _description;
        partial void OndescriptionChanging(global::System.String value);
        partial void OndescriptionChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("SaniteriEntities", "FK_can_Status_can_StatusCode", "can_status")]
        public EntityCollection<can_status> can_status
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<can_status>("SaniteriEntities.FK_can_Status_can_StatusCode", "can_status");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<can_status>("SaniteriEntities.FK_can_Status_can_StatusCode", "can_status", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="SaniteriEntities", Name="can_transaction_log")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class can_transaction_log : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new can_transaction_log object.
        /// </summary>
        /// <param name="seqno">Initial value of the seqno property.</param>
        /// <param name="can_id">Initial value of the can_id property.</param>
        /// <param name="event_time_stamp">Initial value of the event_time_stamp property.</param>
        public static can_transaction_log Createcan_transaction_log(global::System.Guid seqno, global::System.Int64 can_id, global::System.DateTime event_time_stamp)
        {
            can_transaction_log can_transaction_log = new can_transaction_log();
            can_transaction_log.seqno = seqno;
            can_transaction_log.can_id = can_id;
            can_transaction_log.event_time_stamp = event_time_stamp;
            return can_transaction_log;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid seqno
        {
            get
            {
                return _seqno;
            }
            set
            {
                if (_seqno != value)
                {
                    OnseqnoChanging(value);
                    ReportPropertyChanging("seqno");
                    _seqno = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("seqno");
                    OnseqnoChanged();
                }
            }
        }
        private global::System.Guid _seqno;
        partial void OnseqnoChanging(global::System.Guid value);
        partial void OnseqnoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 can_id
        {
            get
            {
                return _can_id;
            }
            set
            {
                Oncan_idChanging(value);
                ReportPropertyChanging("can_id");
                _can_id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("can_id");
                Oncan_idChanged();
            }
        }
        private global::System.Int64 _can_id;
        partial void Oncan_idChanging(global::System.Int64 value);
        partial void Oncan_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime event_time_stamp
        {
            get
            {
                return _event_time_stamp;
            }
            set
            {
                Onevent_time_stampChanging(value);
                ReportPropertyChanging("event_time_stamp");
                _event_time_stamp = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("event_time_stamp");
                Onevent_time_stampChanged();
            }
        }
        private global::System.DateTime _event_time_stamp;
        partial void Onevent_time_stampChanging(global::System.DateTime value);
        partial void Onevent_time_stampChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> event_type
        {
            get
            {
                return _event_type;
            }
            set
            {
                Onevent_typeChanging(value);
                ReportPropertyChanging("event_type");
                _event_type = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("event_type");
                Onevent_typeChanged();
            }
        }
        private Nullable<global::System.Int32> _event_type;
        partial void Onevent_typeChanging(Nullable<global::System.Int32> value);
        partial void Onevent_typeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String event_description
        {
            get
            {
                return _event_description;
            }
            set
            {
                Onevent_descriptionChanging(value);
                ReportPropertyChanging("event_description");
                _event_description = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("event_description");
                Onevent_descriptionChanged();
            }
        }
        private global::System.String _event_description;
        partial void Onevent_descriptionChanging(global::System.String value);
        partial void Onevent_descriptionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String event_data
        {
            get
            {
                return _event_data;
            }
            set
            {
                Onevent_dataChanging(value);
                ReportPropertyChanging("event_data");
                _event_data = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("event_data");
                Onevent_dataChanged();
            }
        }
        private global::System.String _event_data;
        partial void Onevent_dataChanging(global::System.String value);
        partial void Onevent_dataChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String tag_id
        {
            get
            {
                return _tag_id;
            }
            set
            {
                Ontag_idChanging(value);
                ReportPropertyChanging("tag_id");
                _tag_id = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("tag_id");
                Ontag_idChanged();
            }
        }
        private global::System.String _tag_id;
        partial void Ontag_idChanging(global::System.String value);
        partial void Ontag_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String name
        {
            get
            {
                return _name;
            }
            set
            {
                OnnameChanging(value);
                ReportPropertyChanging("name");
                _name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("name");
                OnnameChanged();
            }
        }
        private global::System.String _name;
        partial void OnnameChanging(global::System.String value);
        partial void OnnameChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("SaniteriEntities", "FK_can_EventsLog_can_EventCodes", "can_eventcodes")]
        public can_eventcodes can_eventcodes
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<can_eventcodes>("SaniteriEntities.FK_can_EventsLog_can_EventCodes", "can_eventcodes").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<can_eventcodes>("SaniteriEntities.FK_can_EventsLog_can_EventCodes", "can_eventcodes").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<can_eventcodes> can_eventcodesReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<can_eventcodes>("SaniteriEntities.FK_can_EventsLog_can_EventCodes", "can_eventcodes");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<can_eventcodes>("SaniteriEntities.FK_can_EventsLog_can_EventCodes", "can_eventcodes", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("SaniteriEntities", "FK_can_transaction_log_can_inventory", "can_inventory")]
        public can_inventory can_inventory
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<can_inventory>("SaniteriEntities.FK_can_transaction_log_can_inventory", "can_inventory").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<can_inventory>("SaniteriEntities.FK_can_transaction_log_can_inventory", "can_inventory").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<can_inventory> can_inventoryReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<can_inventory>("SaniteriEntities.FK_can_transaction_log_can_inventory", "can_inventory");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<can_inventory>("SaniteriEntities.FK_can_transaction_log_can_inventory", "can_inventory", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="SaniteriEntities", Name="can_users")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class can_users : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new can_users object.
        /// </summary>
        /// <param name="user_id">Initial value of the user_id property.</param>
        public static can_users Createcan_users(global::System.String user_id)
        {
            can_users can_users = new can_users();
            can_users.user_id = user_id;
            return can_users;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String user_id
        {
            get
            {
                return _user_id;
            }
            set
            {
                if (_user_id != value)
                {
                    Onuser_idChanging(value);
                    ReportPropertyChanging("user_id");
                    _user_id = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("user_id");
                    Onuser_idChanged();
                }
            }
        }
        private global::System.String _user_id;
        partial void Onuser_idChanging(global::System.String value);
        partial void Onuser_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String first_name
        {
            get
            {
                return _first_name;
            }
            set
            {
                Onfirst_nameChanging(value);
                ReportPropertyChanging("first_name");
                _first_name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("first_name");
                Onfirst_nameChanged();
            }
        }
        private global::System.String _first_name;
        partial void Onfirst_nameChanging(global::System.String value);
        partial void Onfirst_nameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String last_name
        {
            get
            {
                return _last_name;
            }
            set
            {
                Onlast_nameChanging(value);
                ReportPropertyChanging("last_name");
                _last_name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("last_name");
                Onlast_nameChanged();
            }
        }
        private global::System.String _last_name;
        partial void Onlast_nameChanging(global::System.String value);
        partial void Onlast_nameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String title
        {
            get
            {
                return _title;
            }
            set
            {
                OntitleChanging(value);
                ReportPropertyChanging("title");
                _title = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("title");
                OntitleChanged();
            }
        }
        private global::System.String _title;
        partial void OntitleChanging(global::System.String value);
        partial void OntitleChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> options
        {
            get
            {
                return _options;
            }
            set
            {
                OnoptionsChanging(value);
                ReportPropertyChanging("options");
                _options = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("options");
                OnoptionsChanged();
            }
        }
        private Nullable<global::System.Int32> _options;
        partial void OnoptionsChanging(Nullable<global::System.Int32> value);
        partial void OnoptionsChanged();

        #endregion
    
    }

    #endregion
    
}
